trigger:
- master

pr:
- master

pool:
  vmImage: vs2017-win2016

steps:
- powershell: .\build.ps1 -target BuildServer
  displayName: Build  
  env:
    NETLIFY_TOKEN: $(NETLIFY_TOKEN)
    
- task: PublishBuildArtifacts@1
  displayName: Publish Website Artifacts
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)\output.zip'
    artifactType: container
    artifactName: Packages
